### ISSUE TITLE
allow masking in subsDT

### ISSUE THREAD

**Issue by mikoontz** [JoshOBrien/rasterDT#1]
Hello!

I noticed that `rasterDT::subsDT()` doesn't produce the same result as `raster::subs()` when trying to replace a value with an NA (i.e., using `subs()` or `subsDT()` as a masking function).

Here's a reproducible example:

```
library(data.table)
library(raster)
# devtools::install_github(repo = "JoshOBrien/rasterDT")
library(rasterDT)
library(viridis)

set.seed(1)
r <- raster(x = matrix(round(10 * rnorm(100)), ncol = 10, nrow = 10))

dict1 <- data.table(original = 6, replacement = NA)

rr1_raster <- raster::subs(x = r, y = dict1, by = "original", which = "replacement", subsWithNA = FALSE)
rr1_rasterDT <- rasterDT::subsDT(x = r, dict = dict1, by = "original", which = "replacement", subsWithNA = FALSE)

par(mfrow = c(1, 2))
plot(rr1_raster, col = viridis(20), main = "{raster}")
text(rr1_raster) # cells with a value of 6 are now NA (depicted in white)

plot(rr1_rasterDT, col = viridis(20), main = "{rasterDT}")
text(rr1_rasterDT) # cells with a value of 6 are still 6
```

Which produces:

![image](https://user-images.githubusercontent.com/11068126/71645480-68038880-2c96-11ea-86b7-4b304d38159f.png)

This is because of [Line 68](https://github.com/JoshOBrien/rasterDT/blob/e9f9a9049fa51b82e13790fdcf0bc5cf6b0f7b54/R/subsDT.R#L68) and [Line 97](https://github.com/JoshOBrien/rasterDT/blob/e9f9a9049fa51b82e13790fdcf0bc5cf6b0f7b54/R/subsDT.R#L97) which each produce the `vals` object (first for the case when processing can happen in memory and the second instance in the case where it cannot). `vals` is a vector the same length as all the values in the raster layer being processed, with NAs when there is no match between the values in the `by` column of the `dict` object, and the corresponding values in the `which` column of the `dict` object when there is a match. Of course, if the desired behavior is to replace a cell value with NA (i.e., the `which` column in the `dict` object is NA), then those replaced values are indistinguishable from the NAs that arise when there is no match!

It might be helpful to be able to mask in this way (essentially replacing a known 'nodata' value with NA) for very large rasters. I also (now) realize that setting the 'nodata' value (using, for example, `{raster}` functions like `raster::NAvalue<-()`) can be a speedy way to accomplish this. But perhaps there is a use case for swapping in NAs (or NaNs) that a different approach (like `rasterDT::subsDT()`) would be good for? In any case, I wanted to point out the difference in behavior between `raster::subs()` and `rasterDT::subsDT()`.

I submitted a pull request that would do this. It uses the `which=` argument in `{data.table}` to return a vector of NAs and index values corresponding to the row number in the `dict` object where there's a match between the `by` column of `dict` and the values of the raster cells. It does not appear to slow down the function (~11.6 hours on a ~29 billion-cell raster using the code as is, and ~9.9 hours on the same raster using the patch-- I assume the faster time for the patch is a fluke, and I only ran the operation once for each variant of the code).

**Comment by JoshOBrien** [comment]
@mikoontz Thanks for this exemplary description of the issue you discovered, and for the pull request. Somehow I didn't get notified of either so am just now seeing this for the first time. I'll have a look as soon as I get a chance, and will get back to you again then.

**Comment by JoshOBrien** [comment]
Closing with de8539319cdf1a4ee12d0dd5551fb2ec448e7a48. Thanks again for pointing out this problem and pinpointing its cause.
